from __future__ import annotations

import json
import os
from pathlib import Path


def main() -> int:
    task = os.getenv("AAS_TASK", "Run a governed CrewAI demo").strip()
    run_id = os.getenv("AAS_RUN_ID", "aas-crewai-demo").strip()
    out_dir = Path("apps") / "crewai_demo"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "aas_crewai_demo.md"
    out_path.write_text(
        "\n".join(
            [
                "# AAS CrewAI Demo",
                "",
                "中文：这个文件由 CrewAI-compatible demo agent 通过 AAS runner 生成。",
                "English: This file was generated by a CrewAI-compatible demo agent through the AAS runner.",
                "",
                f"- Run ID: `{run_id}`",
                f"- Task: {task}",
                "",
            ]
        ),
        encoding="utf-8",
    )
    print(
        json.dumps(
            {
                "summary": "CrewAI-compatible demo generated a governed artifact.",
                "changed_paths": [out_path.as_posix()],
                "recommended_action": "promote",
                "output_artifacts": [
                    {
                        "name": "aas_crewai_demo",
                        "kind": "report",
                        "uri": out_path.as_posix(),
                    }
                ],
            },
            ensure_ascii=False,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
