from __future__ import annotations

import json
from pathlib import Path
import shutil
import sys

from autoresearch.agent_protocol.models import ExecutionPolicy, JobSpec, ValidatorSpec
from autoresearch.core.services.git_promotion_gate import GitPromotionGateService
from autoresearch.executions.runner import AgentExecutionRunner
from autoresearch.shared.models import GitRemoteProbe


class _FakeGitPromotionProvider:
    def probe_remote_health(self, repo_root: Path, *, base_branch: str) -> GitRemoteProbe:
        _ = repo_root, base_branch
        return GitRemoteProbe(
            remote_name="origin",
            remote_url="git@example.invalid/repo.git",
            healthy=True,
            credentials_available=True,
            base_branch_exists=True,
        )

    def create_branch(
        self,
        repo_root: Path,
        *,
        branch_name: str,
        base_branch: str,
        workspace_dir: Path,
    ) -> None:
        _ = repo_root, branch_name, base_branch
        workspace_dir.mkdir(parents=True, exist_ok=True)

    def commit_changes(
        self,
        repo_root: Path,
        *,
        workspace_dir: Path,
        branch_name: str,
        patch_uri: Path,
        changed_files: list[str],
        commit_message: str,
        validator_commands: list[str] | None = None,
        validator_log_dir: Path | None = None,
    ) -> str:
        _ = repo_root, workspace_dir, branch_name, patch_uri, changed_files, commit_message
        _ = validator_commands, validator_log_dir
        return "abc123def456"

    def push_branch(
        self,
        repo_root: Path,
        *,
        workspace_dir: Path,
        branch_name: str,
    ) -> None:
        _ = repo_root, workspace_dir, branch_name

    def open_draft_pr(
        self,
        repo_root: Path,
        *,
        workspace_dir: Path,
        branch_name: str,
        base_branch: str,
        title: str,
        body: str,
    ) -> str:
        _ = repo_root, workspace_dir, title, body
        return f"https://example.invalid/{branch_name}?base={base_branch}"


def _write_manifest(repo_root: Path, entrypoint: str) -> None:
    manifest_path = repo_root / "configs" / "agents" / "autoresearch.yaml"
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(
        json.dumps(
            {
                "id": "autoresearch",
                "kind": "process",
                "entrypoint": entrypoint,
                "version": "0.1",
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )


def _copy_worker_files(repo_root: Path) -> None:
    source_root = Path(__file__).resolve().parents[1]
    source = source_root / "drivers" / "autoresearch_adapter.sh"
    target = repo_root / "drivers" / "autoresearch_adapter.sh"
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, target)
    target.chmod(0o755)


def test_autoresearch_worker_strict_chain_reaches_draft_pr(tmp_path: Path) -> None:
    repo_root = tmp_path / "repo"
    repo_root.mkdir()
    (repo_root / "src").mkdir(parents=True, exist_ok=True)
    (repo_root / "src" / "__init__.py").write_text("", encoding="utf-8")
    _copy_worker_files(repo_root)
    _write_manifest(repo_root, "drivers/autoresearch_adapter.sh")

    promotion_gate = GitPromotionGateService(
        repo_root=repo_root,
        provider=_FakeGitPromotionProvider(),
    )
    runner = AgentExecutionRunner(
        repo_root=repo_root,
        runtime_root=tmp_path / "runtime",
        manifests_dir=repo_root / "configs" / "agents",
        promotion_gate=promotion_gate,
    )

    summary = runner.run_job(
        JobSpec(
            run_id="run-autoresearch-strict",
            agent_id="autoresearch",
            task="Analyze the code and emit a narrow patch suggestion with execution artifacts.",
            validators=[
                ValidatorSpec(
                    id="worker.test_command",
                    kind="command",
                    command=f"{sys.executable} -m py_compile src/autoresearch_generated.py",
                )
            ],
            policy=ExecutionPolicy(
                allowed_paths=["src/autoresearch_generated.py"],
                forbidden_paths=[".git/**", "logs/**", ".masfactory_runtime/**", "memory/**"],
                cleanup_on_success=False,
            ),
            metadata={
                "pipeline_target": "draft_pr",
                "approval_granted": True,
                "branch_name": "codex/autoresearch-worker-strict",
                "pr_title": "AutoResearch strict worker draft",
                "pr_body": "Autogenerated by the strict analysis worker.",
                "deliverables": ["execution_plan", "test_plan", "risk_summary", "patch_suggestion"],
            },
        )
    )

    assert summary.final_status == "promoted"
    assert summary.driver_result.status == "succeeded"
    assert summary.validation.passed is True
    assert summary.promotion is not None
    assert summary.promotion.success is True
    assert summary.promotion.mode.value == "draft_pr"
    assert summary.driver_result.changed_paths == ["src/autoresearch_generated.py"]

    patch_text = Path(summary.promotion_patch_uri or "").read_text(encoding="utf-8")
    assert "src/autoresearch_generated.py" in patch_text
