#!/usr/bin/env bash
set -euo pipefail

require_env() {
  local key="$1"
  if [[ -z "${!key:-}" ]]; then
    echo "[aep][autoresearch] missing env: ${key}" >&2
    exit 40
  fi
}

require_env "AEP_WORKSPACE"
require_env "AEP_ARTIFACT_DIR"
require_env "AEP_JOB_SPEC"
require_env "AEP_RESULT_PATH"
require_env "AEP_BASELINE"

PY_BIN="${PYTHON_BIN:-python3}"

"${PY_BIN}" - "${AEP_JOB_SPEC}" "${AEP_WORKSPACE}" "${AEP_ARTIFACT_DIR}" "${AEP_RESULT_PATH}" "${AEP_BASELINE}" <<'PY'
import json
import re
import sys
from pathlib import Path

job_path = Path(sys.argv[1])
workspace = Path(sys.argv[2])
artifact_dir = Path(sys.argv[3])
result_path = Path(sys.argv[4])
baseline = Path(sys.argv[5])

payload = json.loads(job_path.read_text(encoding="utf-8"))
task = str(payload.get("task") or "autoresearch task").strip()
run_id = str(payload.get("run_id") or "autoresearch-run").strip()
agent_id = str(payload.get("agent_id") or "autoresearch").strip()
policy = payload.get("policy") or {}
metadata = payload.get("metadata") or {}
allowed_paths = list(policy.get("allowed_paths") or [])
deliverables = list(metadata.get("deliverables") or ["execution_plan", "test_plan", "risk_summary", "patch_suggestion"])

def pick_target(patterns: list[str]) -> Path:
    for pattern in patterns:
        if not any(char in pattern for char in "*?["):
            return workspace / pattern
    for pattern in patterns:
        prefix = pattern.split("*", 1)[0].split("?", 1)[0].split("[", 1)[0].rstrip("/")
        if prefix:
            if "." in Path(prefix).name:
                return workspace / prefix
            return workspace / prefix / "autoresearch_worker_output.py"
    return workspace / "src" / "autoresearch_worker_output.py"

target = pick_target(allowed_paths)
target.parent.mkdir(parents=True, exist_ok=True)
safe_task = task.replace('"""', "'''")

if target.suffix == ".py":
    target.write_text(
        '"""Generated by the AutoResearch AEP adapter."""\n\n'
        "def plan() -> dict[str, str]:\n"
        f'    return {{"run_id": "{run_id}", "task": "{safe_task}", "status": "suggested"}}\n',
        encoding="utf-8",
    )
else:
    target.write_text(
        f"AutoResearch patch candidate\n\nTask: {task}\n",
        encoding="utf-8",
    )

artifact_dir.mkdir(parents=True, exist_ok=True)
artifact_refs = []

def write_artifact(name: str, content: str, kind: str) -> None:
    path = artifact_dir / f"{name}.md"
    path.write_text(content, encoding="utf-8")
    artifact_refs.append({"name": name, "kind": kind, "uri": str(path), "sha256": None})

if "execution_plan" in deliverables:
    write_artifact(
        "execution_plan",
        "# Execution Plan\n\n"
        f"- Scope target: `{target.relative_to(workspace).as_posix()}`\n"
        f"- Research task: {task}\n"
        "- Emit a narrow patch candidate inside allowed_paths.\n",
        "plan",
    )
if "test_plan" in deliverables:
    validators = payload.get("validators") or []
    command = ""
    for item in validators:
        if item.get("kind") == "command" and item.get("command"):
            command = str(item["command"])
            break
    write_artifact(
        "test_plan",
        "# Test Plan\n\n"
        f"- Validate with: `{command}`\n"
        "- Fail closed if the validator does not pass.\n",
        "plan",
    )
if "risk_summary" in deliverables:
    write_artifact(
        "risk_summary",
        "# Risk Summary\n\n"
        "- No direct git writes.\n"
        "- No direct promotion finalize.\n"
        "- Scope stays inside allowed_paths.\n",
        "report",
    )
if "patch_suggestion" in deliverables:
    write_artifact(
        "patch_suggestion",
        "# Patch Suggestion\n\n"
        f"- Candidate target: `{target.relative_to(workspace).as_posix()}`\n"
        "- Promotion remains gated.\n",
        "report",
    )

base_files = {p.relative_to(baseline).as_posix() for p in baseline.rglob("*") if p.is_file()}
workspace_files = {p.relative_to(workspace).as_posix() for p in workspace.rglob("*") if p.is_file()}
changed = []
for rel in sorted(base_files | workspace_files):
    base_path = baseline / rel
    ws_path = workspace / rel
    if not base_path.exists() or not ws_path.exists():
        changed.append(rel)
        continue
    if base_path.read_bytes() != ws_path.read_bytes():
        changed.append(rel)

result = {
    "protocol_version": "aep/v0",
    "run_id": run_id,
    "agent_id": agent_id,
    "attempt": 1,
    "status": "succeeded",
    "summary": "autoresearch adapter produced scoped artifacts and a patch candidate",
    "changed_paths": changed,
    "output_artifacts": artifact_refs,
    "metrics": {
        "duration_ms": 0,
        "steps": 1,
        "commands": 0,
        "prompt_tokens": None,
        "completion_tokens": None,
    },
    "recommended_action": "promote",
    "error": None,
}
result_path.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
PY
