#!/usr/bin/env bash
set -euo pipefail

require_env() {
  local key="$1"
  if [[ -z "${!key:-}" ]]; then
    echo "[aep][mock] missing env: ${key}" >&2
    exit 40
  fi
}

require_env "AEP_WORKSPACE"
require_env "AEP_JOB_SPEC"
require_env "AEP_RESULT_PATH"

PY_BIN="${PYTHON_BIN:-python3}"

"${PY_BIN}" - "${AEP_JOB_SPEC}" "${AEP_WORKSPACE}" "${AEP_RESULT_PATH}" <<'PY'
import json
import re
import sys
from pathlib import Path

job_path = Path(sys.argv[1])
workspace = Path(sys.argv[2])
result_path = Path(sys.argv[3])

payload = json.loads(job_path.read_text(encoding="utf-8"))
task = str(payload.get("task") or "mock task").strip()
run_id = str(payload.get("run_id") or "mock-run").strip()
agent_id = str(payload.get("agent_id") or "mock").strip()

slug = re.sub(r"[^a-z0-9]+", "_", task.lower()).strip("_") or "task"
target = workspace / "src" / "mock_agent_output.py"
target.parent.mkdir(parents=True, exist_ok=True)
content = (
    '"""Generated by the mock AEP adapter."""\n\n'
    "def run() -> dict[str, str]:\n"
    f'    return {{"run_id": "{run_id}", "task": "{slug}", "status": "mocked"}}\n'
)
target.write_text(content, encoding="utf-8")

result = {
    "protocol_version": "aep/v0",
    "run_id": run_id,
    "agent_id": agent_id,
    "attempt": 1,
    "status": "succeeded",
    "summary": "mock adapter produced a synthetic patch",
    "changed_paths": ["src/mock_agent_output.py"],
    "output_artifacts": [],
    "metrics": {
        "duration_ms": 0,
        "steps": 1,
        "commands": 0,
        "prompt_tokens": None,
        "completion_tokens": None,
    },
    "recommended_action": "promote",
    "error": None,
}
result_path.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
PY
