#!/usr/bin/env bash
set -euo pipefail

require_env() {
  local key="$1"
  if [[ -z "${!key:-}" ]]; then
    echo "[aep][mock] missing env: ${key}" >&2
    exit 40
  fi
}

require_env "AEP_WORKSPACE"
require_env "AEP_JOB_SPEC"
require_env "AEP_RESULT_PATH"

PY_BIN="${PYTHON_BIN:-python3}"

"${PY_BIN}" - "${AEP_JOB_SPEC}" "${AEP_WORKSPACE}" "${AEP_RESULT_PATH}" <<'PY'
import fnmatch
import json
import re
import shlex
import sys
from pathlib import Path
from typing import Optional

job_path = Path(sys.argv[1])
workspace = Path(sys.argv[2])
result_path = Path(sys.argv[3])

payload = json.loads(job_path.read_text(encoding="utf-8"))
task = str(payload.get("task") or "mock task").strip()
run_id = str(payload.get("run_id") or "mock-run").strip()
agent_id = str(payload.get("agent_id") or "mock").strip()
policy = payload.get("policy") or {}
allowed_paths = [
    str(item).strip()
    for item in policy.get("allowed_paths") or []
    if isinstance(item, str) and str(item).strip()
]
validators = payload.get("validators") or []
validator_command = ""
for spec in validators:
    if isinstance(spec, dict) and str(spec.get("kind") or "") == "command":
        validator_command = str(spec.get("command") or "").strip()
        if validator_command:
            break

slug = re.sub(r"[^a-z0-9]+", "_", task.lower()).strip("_") or "task"


def matches_any(path: str, patterns: list[str]) -> bool:
    normalized = path.replace("\\", "/")
    return any(fnmatch.fnmatch(normalized, pattern) for pattern in patterns)


def infer_validator_target() -> Optional[Path]:
    if not validator_command:
        return None
    for token in reversed(shlex.split(validator_command)):
        candidate = token.strip().strip("'\"").replace("\\", "/")
        if not candidate or candidate.startswith("-"):
            continue
        if candidate in {"python", "python3", "pytest", "py_compile"}:
            continue
        if not any(marker in candidate for marker in ("/", ".")):
            continue
        if matches_any(candidate, allowed_paths):
            return workspace / candidate
    return None


def infer_primary_source_target() -> Optional[Path]:
    exact_paths = [
        item
        for item in allowed_paths
        if not any(char in item for char in "*?[") and "/tests/" not in f"/{item.replace('\\', '/')}/"
    ]
    for candidate in exact_paths:
        path = Path(candidate)
        if path.name.startswith("test_") and "tests" in path.parts:
            continue
        return workspace / candidate

    for pattern in allowed_paths:
        prefix = pattern.split("*", 1)[0].split("?", 1)[0].split("[", 1)[0].rstrip("/")
        if not prefix:
            continue
        prefix_path = Path(prefix)
        if prefix_path.name.startswith("test_") and "tests" in prefix_path.parts:
            continue
        if "." in prefix_path.name:
            return workspace / prefix
        if "apps" in prefix_path.parts:
            return workspace / prefix / "lead_capture.py"
        return workspace / prefix / "mock_agent_output.py"
    return None


def select_target() -> Path:
    inferred = infer_validator_target()
    if inferred is not None:
        return inferred

    exact_paths = [item for item in allowed_paths if not any(char in item for char in "*?[")]
    for candidate in exact_paths:
        if candidate and candidate in validator_command:
            return workspace / candidate
    for candidate in exact_paths:
        path = Path(candidate)
        if path.name.startswith("test_") and "tests" in path.parts:
            return workspace / candidate
    if exact_paths:
        return workspace / exact_paths[0]
    for pattern in allowed_paths:
        prefix = pattern.split("*", 1)[0].split("?", 1)[0].split("[", 1)[0].rstrip("/")
        if not prefix:
            continue
        if "." in Path(prefix).name:
            return workspace / prefix
        return workspace / prefix / "mock_agent_output.py"
    return workspace / "src" / "mock_agent_output.py"


def build_source_content(target_path: Path) -> str:
    relative = target_path.relative_to(workspace)
    if relative.name == "lead_capture.py" and "apps" in relative.parts:
        return (
            '"""Generated by the mock AEP adapter."""\n\n'
            "import re\n\n"
            "PHONE_PATTERN = re.compile(r'^1[3-9]\\\\d{9}$')\n\n"
            "class PhoneValidator:\n"
            "    @staticmethod\n"
            "    def validate(phone: str) -> bool:\n"
            "        normalized = str(phone or '').replace(' ', '').replace('-', '')\n"
            "        return bool(PHONE_PATTERN.fullmatch(normalized))\n\n"
            "def capture_lead(phone: str) -> dict[str, object]:\n"
            "    if not PhoneValidator.validate(phone):\n"
            "        return {'success': False, 'error': 'invalid_phone_format'}\n"
            "    normalized = str(phone).replace(' ', '').replace('-', '')\n"
            "    return {'success': True, 'phone_masked': normalized[:3] + '****' + normalized[-4:]}\n"
        )
    return (
        '"""Generated by the mock AEP adapter."""\n\n'
        "def run() -> dict[str, str]:\n"
        f'    return {{"run_id": "{run_id}", "task": "{slug}", "status": "mocked"}}\n'
    )


def build_test_content(target_path: Path, source_target: Path) -> str:
    relative_source = source_target.relative_to(workspace)
    module_name = ".".join(relative_source.with_suffix("").parts)
    if relative_source.name == "lead_capture.py":
        return (
            '"""Generated by the mock AEP adapter."""\n\n'
            f"from {module_name} import PhoneValidator, capture_lead\n\n"
            "def test_phone_validator_accepts_normalized_mobile() -> None:\n"
            "    assert PhoneValidator.validate('13812345678') is True\n"
            "    assert PhoneValidator.validate('138 1234 5678') is True\n"
            "    assert PhoneValidator.validate('12812345678') is False\n\n"
            "def test_capture_lead_masks_phone() -> None:\n"
            "    result = capture_lead('13812345678')\n"
            "    assert result['success'] is True\n"
            "    assert result['phone_masked'].startswith('138')\n"
            "    assert '12345678' not in result['phone_masked']\n"
        )
    return (
        '"""Generated by the mock AEP adapter."""\n\n'
        "def test_mock_autoresearch_candidate() -> None:\n"
        "    assert True\n"
    )


target = select_target()
source_target = infer_primary_source_target() or target
changed_paths: list[str] = []

if (
    target.name.startswith("test_")
    and "tests" in target.relative_to(workspace).parts
    and "apps" in source_target.relative_to(workspace).parts
):
    source_target.parent.mkdir(parents=True, exist_ok=True)
    source_target.write_text(build_source_content(source_target), encoding="utf-8")
    changed_paths.append(source_target.relative_to(workspace).as_posix())

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(build_test_content(target, source_target), encoding="utf-8")
    changed_paths.append(target.relative_to(workspace).as_posix())
else:
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.name.startswith("test_") and "tests" in target.relative_to(workspace).parts:
        target.write_text(build_test_content(target, source_target), encoding="utf-8")
    else:
        target.write_text(build_source_content(target), encoding="utf-8")
    changed_paths.append(target.relative_to(workspace).as_posix())

result = {
    "protocol_version": "aep/v0",
    "run_id": run_id,
    "agent_id": agent_id,
    "attempt": 1,
    "status": "succeeded",
    "summary": "mock adapter produced a synthetic patch",
    "changed_paths": changed_paths,
    "output_artifacts": [],
    "metrics": {
        "duration_ms": 0,
        "steps": 1,
        "commands": 0,
        "prompt_tokens": None,
        "completion_tokens": None,
    },
    "recommended_action": "promote",
    "error": None,
}
result_path.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
PY
