#!/usr/bin/env bash
set -euo pipefail

require_env() {
  local key="$1"
  if [[ -z "${!key:-}" ]]; then
    echo "[aep][mock] missing env: ${key}" >&2
    exit 40
  fi
}

require_env "AEP_WORKSPACE"
require_env "AEP_JOB_SPEC"
require_env "AEP_RESULT_PATH"

PY_BIN="${PYTHON_BIN:-python3}"

"${PY_BIN}" - "${AEP_JOB_SPEC}" "${AEP_WORKSPACE}" "${AEP_RESULT_PATH}" <<'PY'
import json
import re
import sys
from pathlib import Path

job_path = Path(sys.argv[1])
workspace = Path(sys.argv[2])
result_path = Path(sys.argv[3])

payload = json.loads(job_path.read_text(encoding="utf-8"))
task = str(payload.get("task") or "mock task").strip()
run_id = str(payload.get("run_id") or "mock-run").strip()
agent_id = str(payload.get("agent_id") or "mock").strip()
policy = payload.get("policy") or {}
allowed_paths = [
    str(item).strip()
    for item in policy.get("allowed_paths") or []
    if isinstance(item, str) and str(item).strip()
]
validators = payload.get("validators") or []
validator_command = ""
for spec in validators:
    if isinstance(spec, dict) and str(spec.get("kind") or "") == "command":
        validator_command = str(spec.get("command") or "").strip()
        if validator_command:
            break

slug = re.sub(r"[^a-z0-9]+", "_", task.lower()).strip("_") or "task"


def select_target() -> Path:
    exact_paths = [item for item in allowed_paths if not any(char in item for char in "*?[")]
    for candidate in exact_paths:
        if candidate and candidate in validator_command:
            return workspace / candidate
    for candidate in exact_paths:
        path = Path(candidate)
        if path.name.startswith("test_") and "tests" in path.parts:
            return workspace / candidate
    if exact_paths:
        return workspace / exact_paths[0]
    return workspace / "src" / "mock_agent_output.py"


def build_content(target_path: Path) -> str:
    relative = target_path.relative_to(workspace)
    if relative.name.startswith("test_") and "tests" in relative.parts:
        return (
            '"""Generated by the mock AEP adapter."""\n\n'
            "def test_mock_autoresearch_candidate() -> None:\n"
            "    assert True\n"
        )
    return (
        '"""Generated by the mock AEP adapter."""\n\n'
        "def run() -> dict[str, str]:\n"
        f'    return {{"run_id": "{run_id}", "task": "{slug}", "status": "mocked"}}\n'
    )


target = select_target()
target.parent.mkdir(parents=True, exist_ok=True)
content = build_content(target)
target.write_text(content, encoding="utf-8")
changed_path = target.relative_to(workspace).as_posix()

result = {
    "protocol_version": "aep/v0",
    "run_id": run_id,
    "agent_id": agent_id,
    "attempt": 1,
    "status": "succeeded",
    "summary": "mock adapter produced a synthetic patch",
    "changed_paths": [changed_path],
    "output_artifacts": [],
    "metrics": {
        "duration_ms": 0,
        "steps": 1,
        "commands": 0,
        "prompt_tokens": None,
        "completion_tokens": None,
    },
    "recommended_action": "promote",
    "error": None,
}
result_path.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
PY
