#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import shutil
import tempfile
from pathlib import Path

from autoresearch.agent_protocol.models import JobSpec
from autoresearch.executions.runner import AgentExecutionRunner


def _write_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _build_demo_repo(repo_root: Path, source_root: Path) -> None:
    _write_file(repo_root / "README.md", "# CrewAI demo workspace\n")
    (repo_root / "drivers").mkdir(parents=True, exist_ok=True)
    shutil.copy2(source_root / "drivers" / "crewai_adapter.py", repo_root / "drivers" / "crewai_adapter.py")
    (repo_root / "drivers" / "crewai_adapter.py").chmod(0o755)
    _write_file(
        repo_root / "configs" / "agents" / "aas_crewai_demo.yaml",
        json.dumps(
            {
                "id": "aas_crewai_demo",
                "kind": "process",
                "entrypoint": "drivers/crewai_adapter.py",
                "execution_semantics": "patch",
                "capabilities": ["crewai", "produce_patchable_changes"],
                "default_mode": "apply_in_workspace",
                "policy_defaults": {
                    "timeout_sec": 60,
                    "allowed_paths": ["apps/**"],
                    "forbidden_paths": [".git/**", "logs/**", ".masfactory_runtime/**", "memory/**"],
                    "max_changed_files": 5,
                    "max_patch_lines": 500,
                    "cleanup_on_success": True,
                    "retain_workspace_on_failure": True,
                },
                "metadata": {
                    "crewai": {
                        "entrypoint": "examples.crewai_agents.aas_crewai_demo.crew",
                        "require_package": False,
                    }
                },
            },
            ensure_ascii=False,
            indent=2,
        ),
    )
    _write_file(repo_root / "examples" / "__init__.py", "")
    _write_file(repo_root / "examples" / "crewai_agents" / "__init__.py", "")
    _write_file(repo_root / "examples" / "crewai_agents" / "aas_crewai_demo" / "__init__.py", "")
    _write_file(
        repo_root / "examples" / "crewai_agents" / "aas_crewai_demo" / "crew.py",
        """
from __future__ import annotations

import json
import os
from pathlib import Path

task = os.getenv("AAS_TASK", "Run CrewAI demo").strip()
out = Path("apps") / "crewai_demo" / "aas_crewai_demo.md"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(
    "# AAS CrewAI Demo\\n\\n"
    "中文：这个产物由 CrewAI-compatible agent 通过 AAS runner 生成。\\n"
    "English: This artifact was generated by a CrewAI-compatible agent through the AAS runner.\\n\\n"
    f"Task: {task}\\n",
    encoding="utf-8",
)
print(json.dumps({"summary": "CrewAI demo completed.", "changed_paths": [out.as_posix()], "recommended_action": "promote"}))
""",
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run a small governed CrewAI-compatible demo")
    parser.add_argument("--task", default="Produce a governed CrewAI demo artifact.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    source_root = Path(__file__).resolve().parents[1]
    with tempfile.TemporaryDirectory(prefix="aas-crewai-demo-") as tmp:
        demo_root = Path(tmp) / "repo"
        runtime_root = Path(tmp) / "runtime"
        demo_root.mkdir(parents=True)
        _build_demo_repo(demo_root, source_root)
        runner = AgentExecutionRunner(
            repo_root=demo_root,
            runtime_root=runtime_root,
            manifests_dir=demo_root / "configs" / "agents",
        )
        summary = runner.run_job(
            JobSpec(run_id="crewai-demo", agent_id="aas_crewai_demo", task=args.task)
        )
        print(json.dumps(summary.model_dump(mode="json"), ensure_ascii=False, indent=2))
        return 0 if summary.final_status == "ready_for_promotion" else 2


if __name__ == "__main__":
    raise SystemExit(main())
