"""README generation for content knowledge base repositories."""

from __future__ import annotations

import logging
from pathlib import Path

from content_kb.contracts import SpeakerIndex, TimelineIndex, TopicIndex

logger = logging.getLogger(__name__)


def generate_repo_readme(
    repo_name: str,
    topic: str,
    topic_index: TopicIndex | None = None,
    speaker_index: SpeakerIndex | None = None,
    timeline_index: TimelineIndex | None = None,
) -> str:
    """Generate README.md content for a knowledge base repository.

    Args:
        repo_name: Name of the repository
        topic: Primary topic of this repository
        topic_index: Optional topic statistics
        speaker_index: Optional speaker statistics
        timeline_index: Optional timeline data

    Returns:
        README.md content as string
    """
    lines = [
        f"# {repo_name}",
        "",
        f"Topic: **{topic}**",
        "",
        "## Content Statistics",
        "",
    ]

    if topic_index:
        entry = topic_index.topics.get(topic)
        if entry:
            lines.extend([
                f"- **Total Entries**: {entry.count}",
                f"- **Latest**: {entry.latest_title or 'N/A'}",
                "",
            ])

    if speaker_index and speaker_index.speakers:
        lines.append("## Speakers")
        lines.append("")
        for speaker, data in sorted(
            speaker_index.speakers.items(),
            key=lambda x: x[1].appearances,
            reverse=True,
        )[:10]:
            lines.append(f"- **{speaker}**: {data.appearances} appearances")
        lines.append("")

    if timeline_index and timeline_index.entries:
        lines.append("## Recent Timeline")
        lines.append("")
        for entry in timeline_index.entries[:5]:
            lines.append(f"- **{entry.date}**: {entry.title}")
        lines.append("")

    lines.extend([
        "---",
        "",
        "*This README is auto-generated by the content_kb agent.*",
        "",
        f"*Last updated: {timeline_index.updated_at if timeline_index else 'N/A'}*",
    ])

    return "\n".join(lines)


def write_repo_readme(
    repo_path: Path,
    topic: str,
    topic_index: TopicIndex | None = None,
    speaker_index: SpeakerIndex | None = None,
    timeline_index: TimelineIndex | None = None,
) -> Path:
    """Write README.md to a knowledge base repository.

    Args:
        repo_path: Path to the repository root
        topic: Primary topic of this repository
        topic_index: Optional topic statistics
        speaker_index: Optional speaker statistics
        timeline_index: Optional timeline data

    Returns:
        Path to the written README.md
    """
    repo_name = repo_path.name
    content = generate_repo_readme(
        repo_name,
        topic,
        topic_index,
        speaker_index,
        timeline_index,
    )

    readme_path = repo_path / "README.md"
    readme_path.write_text(content, encoding="utf-8")
    logger.info(f"Written README to {readme_path}")

    return readme_path
