import { NextResponse } from 'next/server'

export async function GET() {
  const agents = [
    {
      id: 'planner',
      name: 'Planner Agent',
      status: 'running',
      successRate: 92.3,
      tasksCompleted: 145,
      avgResponseTime: '1.2s',
      lastActivity: new Date(Date.now() - 120000).toISOString(),
      role: '规划节点，对接 OpenClaw',
    },
    {
      id: 'generator',
      name: 'Generator Agent',
      status: 'running',
      successRate: 88.7,
      tasksCompleted: 132,
      avgResponseTime: '0.9s',
      lastActivity: new Date(Date.now() - 60000).toISOString(),
      role: '生成节点，写代码或调用工具',
    },
    {
      id: 'executor',
      name: 'Executor Agent',
      status: 'running',
      successRate: 95.1,
      tasksCompleted: 167,
      avgResponseTime: '2.3s',
      lastActivity: new Date(Date.now() - 30000).toISOString(),
      role: '执行节点，沙盒环境',
    },
    {
      id: 'evaluator',
      name: 'Evaluator Agent',
      status: 'running',
      successRate: 90.4,
      tasksCompleted: 156,
      avgResponseTime: '1.5s',
      lastActivity: new Date(Date.now() - 45000).toISOString(),
      role: '评估节点，承载 MetaClaw 逻辑',
    },
    {
      id: 'telegram-gateway',
      name: 'Telegram Gateway',
      status: 'running',
      successRate: 99.2,
      tasksCompleted: 289,
      avgResponseTime: '0.3s',
      lastActivity: new Date(Date.now() - 10000).toISOString(),
      role: 'Telegram 消息网关',
    },
    {
      id: 'web-panel',
      name: 'Web Panel Agent',
      status: 'running',
      successRate: 97.8,
      tasksCompleted: 178,
      avgResponseTime: '0.5s',
      lastActivity: new Date(Date.now() - 20000).toISOString(),
      role: 'Web 面板管理',
    },
    {
      id: 'dynamic-tool',
      name: 'Dynamic Tool Agent',
      status: 'idle',
      successRate: 86.5,
      tasksCompleted: 98,
      avgResponseTime: '3.2s',
      lastActivity: new Date(Date.now() - 300000).toISOString(),
      role: '动态工具执行（Docker 沙盒）',
    },
    {
      id: 'openviking',
      name: 'OpenViking Agent',
      status: 'running',
      successRate: 94.6,
      tasksCompleted: 112,
      avgResponseTime: '1.8s',
      lastActivity: new Date(Date.now() - 90000).toISOString(),
      role: '记忆压缩与优化',
    },
    {
      id: 'mirofish',
      name: 'MiroFish Agent',
      status: 'running',
      successRate: 89.2,
      tasksCompleted: 87,
      avgResponseTime: '0.7s',
      lastActivity: new Date(Date.now() - 150000).toISOString(),
      role: '预测旁路与闸门控制',
    },
    {
      id: 'self-integration',
      name: 'Self Integration Agent',
      status: 'idle',
      successRate: 78.9,
      tasksCompleted: 34,
      avgResponseTime: '4.5s',
      lastActivity: new Date(Date.now() - 600000).toISOString(),
      role: '自主集成协议（Discover/Prototype/Promote）',
    },
  ]

  return NextResponse.json({ agents, total: agents.length })
}
